showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
theme: 1
latencyTimeout: 3000
editor: 0
iconSpeed: false
lightweightMode: false
latencyUrl: ""
useSystemEmoji: true
systemTheme: false
mixinText: |-
  mixin: # object
    dns:
      enable: true
      enhanced-mode: redir-host
      nameserver:
        - 8.8.4.4
        - 1.1.1.1
childProcessText: |
  processes: # array
profileParsersText: |+
  parsers: # array
    - url: https://dogess.work/link/PLGEHBrTklGAW9yj?clash=1
      yaml:
        prepend-proxies:
          - name: "Azure HK"
            type: vmess
            server: pandapandaaweb.com
            port: 443
            uuid: 3c79046b-c4f2-42b2-a233-f3b5f62798ed
            alterId: 0
            cipher: auto
            tls: true
            network: ws
            ws-path: /
            ws-headers:
            Host: pandapandaaweb.com
        commands:
          - proxy-groups.(🍃 Proxies).proxies+[]proxyNames|Azure HK|AIA|专线

