#!/usr/bin/env sh

source "$HOME/.config/sketchybar/color.sh"

PLUGIN_DIR="$HOME/.config/sketchybar/controller"
BAR_SIZE=32
FONT_SIZE=12

ITEM_DIR="$HOME/.config/sketchybar/view"

PADDING=4
ICON="SF Symbols"
LABEL="JetBrainsMono Nerd Font Mono"

sketchybar --bar height=$BAR_SIZE \
	blur_radius=0 \
	padding_left=4 \
	padding_right=4 \
	color=0xff16161e \
	position=top \
	sticky=on \
	font_smoothing=on \
	--default updates=when_shown \
	drawing=on \
	icon.font="$ICON:Medium:$FONT_SIZE.0" \
	label.font="$LABEL:Medium:$FONT_SIZE.0" \
	icon.padding_left=$PADDING \
	icon.padding_right=$PADDING \
	label.padding_left=$PADDING \
	label.padding_right=$PADDING \
	label.color=0xffa9b1d6 \
	icon.color=0xffa9b1d6

# left
source "$ITEM_DIR/space.sh"
source "$ITEM_DIR/front_app.sh"

# right
source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/disk.sh"
source "$ITEM_DIR/mem.sh"
# source "$ITEM_DIR/cpu.sh"

# initializing
sketchybar --update

echo "sketchybar configuration loaded.."
