#!/bin/bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

DEFAUL_LAYOUT="bsp"
SOCIAL_LAYOUT="stack"
OTHER_LAYOUT="float"

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
	  yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"

  if [[ $name == "im" ]]; then
	yabai -m space $idx --layout $SOCIAL_LAYOUT
  else
	yabai -m space $idx --layout $DEFAUL_LAYOUT
  fi
}

setup_space 1 term
setup_space 2 code
setup_space 3 emacs
setup_space 4 web 
setup_space 5 im
setup_space 6 mail
setup_space 7 other

yabai -m config top_padding  	10
yabai -m config bottom_padding 	10
yabai -m config left_padding   	10
yabai -m config right_padding  	10
yabai -m config window_gap     	10

yabai -m config window_shadow off
yabai -m config window_opacity on
yabai -m config active_window_opacity 0.9
yabai -m config normal_window_opacity 0.75

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Infuse" opacity=1.0

# space 1
yabai -m rule --add app="^Alacritty" space=^1

# space 2
yabai -m rule --add app="^Code" space=^2

# space 3
yabai -m rule --add app="^Emacs" space=^3

# space 4
yabai -m rule --add app="^Arc" space=^4 opacity=1.0 
yabai -m rule --add app="^Safari" space=^4 opacity=1.0
yabai -m rule --add app="^Firefox" space=^4 opacity=1.0

# space 5
yabai -m rule --add app="^WeChat" space=^5 opacity=1.0
yabai -m rule --add app="^Message" space=^5 opacity=1.0
yabai -m rule --add app="^Skype" space=^5 opacity=1.0
yabai -m rule --add app="^Microsoft Teams" space=^5 opacity=1.0
yabai -m rule --add app="^Slack" space=^5 opacity=1.0

# space 6
yabai -m rule --add app="^Spark" space=^6
yabai -m rule --add app="^Microsoft Outlook" space=^6

# space 7
yabai -m rule --add app="^Parallels Desktop" space=^7



