#!/bin/bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

DEFAUL_LAYOUT="bsp"
SOCIAL_LAYOUT="stack"
NOTCH_UUID="37D8832A-2D66-02CA-B9F7-8F30A301B230"
NOTCH_BAR=10
NORMAL_BAR=40

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
	  yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"

  if [[ $name == "im" ]]; then
	yabai -m space $idx --layout $SOCIAL_LAYOUT
  else
	yabai -m space $idx --layout $DEFAUL_LAYOUT
  fi
}
setup_space 1 term
setup_space 2 emacs
setup_space 3 web 
setup_space 4 im
setup_space 5 mail
setup_space 6 other

yabai -m config top_padding  10
yabai -m config bottom_padding 10
yabai -m config left_padding   10
yabai -m config right_padding  10
yabai -m config window_gap     10

yabai -m config window_shadow off
yabai -m config window_opacity on
yabai -m config active_window_opacity 0.93
yabai -m config normal_window_opacity 0.75

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Safari" space=^3
yabai -m rule --add app="^Firefox" space=^3
yabai -m rule --add app="^Alacritty" space=^1
yabai -m rule --add app="^Emacs" space=^2
yabai -m rule --add app="^WeChat" space=^4 opacity=1.0
yabai -m rule --add app="^Skype" space=^4 opacity=1.0
yabai -m rule --add app="^Slack" space=^4 opacity=1.0
yabai -m rule --add app="^Spark" space=^5


